language: go

go:
  - 1.3

node_js:
  - "5"
  - "4"

install:
  - npm install
  - npm install -g grunt-cli
  - go get github.com/tools/godep
  - git clone https://github.com/EagerIO/Stout.git
  - cd Stout; godep go build -o ../stout src/*.go

script:
  - grunt build
  - stout